### ISSUE TITLE
Erreurs de trame

### ISSUE THREAD

**Issue by mathrb** [lhuet/teleinfo-node#2]
Bonjour,
Le module plante de deux manières : 
La première sur une erreur de checksum : 

```
Error: Erreur de checksum :

C
OPTARIF BASE 0
 Checksum calculé/reçu : 33 / 48
```

La deuxième sur le module serial : 

```
Error: Trame incomplete
    at EventEmitter.<anonymous> (/home/pi/teleinfo-client/node_modules/teleinfo/teleinfo.js:38:29)
    at EventEmitter.emit (events.js:117:20)
    at SerialPort.<anonymous> (/home/pi/teleinfo-client/node_modules/teleinfo/teleinfo.js:19:15)
    at SerialPort.emit (events.js:95:17)
    at /home/pi/teleinfo-client/node_modules/teleinfo/node_modules/serialport/serialport.js:52:19
    at Array.forEach (native)
    at Object.parser (/home/pi/teleinfo-client/node_modules/teleinfo/node_modules/serialport/serialport.js:51:15)
    at Object.SerialPort.options.dataCallback (/home/pi/teleinfo-client/node_modules/teleinfo/node_modules/serialport/serialport.js:164:15)
    at SerialPortFactory.SerialPort._emitData (/home/pi/teleinfo-client/node_modules/teleinfo/node_modules/serialport/serialport.js:355:22)
    at afterRead (/home/pi/teleinfo-client/node_modules/teleinfo/node_modules/serialport/serialport.js:325:18)
```

Avez-vous rencontré ce problème, comptez vous maintenir le module ?

Cordialement
Mathias

**Comment by alexpalex9** [comment]
Personnellement, j'ai réécrit le module. J'avais un souci sur le port et j'ai réalisé quelques ajustements sur la longueur de Trame.
Depuis hier soir, j'ai également beaucoup d'erreur qui surviennent. Peut-être le froid? ou un changement chez EDF? ou mon lecteur qui fatigue

**Comment by zdid** [comment]
Apparamment le module ne serait plus maintenu, dommage.
J'ai voulu l'installer sur un node 6.9, mais il n'est pas passé, notamment du fiait de l'utilisation de serialport trop ancien.
